### ISSUE TITLE
Interactive add (git add -p) impossible with transcrypt 

### ISSUE THREAD

**Issue by hsanson** [elasticdog/transcrypt#15]
Doing a git diff I get to see the code differences ok but trying a "git add -p" shows only the encrypted content making it impossible to commit blocks of code.

**Comment by elasticdog** [comment]
Yes, this is a limitation in how Git [textconv filters](https://www.kernel.org/pub/software/scm/git/docs/gitattributes.html#_tt_filter_tt) work (which is what transcrypt sets up in your repository). Since adding patch hunks updates the index, and updating the index is when the textconv filter is applied (i.e. when your data gets encrypted), it will not work as expected. I believe if Git had some sort of built-in mechanism to special case patch hunks in a similar fashion as they do diff display, then it could work, but right now that's not the case.

To make working with transcrypt easier, a pattern that I'd suggest would be to to define variables with all of the sensitive data and store them in a dedicated file that is then encrypted with transcrypt. The regular code would then remain unencrypted and simply reference the variables from that file (via templating or whatever method). That way you don't have to store the sensitive information inline, or in files that change regularly where you'd want to stage hunks on a regular basis. Hope that helps.

**Comment by hsanson** [comment]
Too bad there is no solution for this problem. Solving one line conflicts when using transcrypt is far more complicated than it should....
