### ISSUE TITLE
openssl: WARNING : deprecated key derivation used. Using -iter or -pbkdf2 would be better.

### ISSUE THREAD

**Issue by njfamirm** [elasticdog/transcrypt#169]
hi
when I'm update openssl to latest 
```
λ openssl version
LibreSSL 3.3.6
```
```
λ transcrypt --version
transcrypt 2.2.3
```

and when I'm use transcrypt, have this warning in cli
```
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
```

how can fix this?

https://www.phind.com/search?cache=2644031a-8c01-4f24-8ba8-60bdc30e9aba

**Comment by njfamirm** [comment]
please help me!

**Comment by jmurty** [comment]
Hi @njfamirm the warning message is from OpenSSL, you can ignore those messages because _transcrypt_ will still work fine. It just isn't the strongest encryption algorithm it could.

This is a known issue. Removing those warnings requires a new encryption approach to use the PBKDF2 algorithm, which we are working on, but slowly. See related issues #55, #59, #134 and a few [pull requests](https://github.com/elasticdog/transcrypt/pulls) where we are working on it.
