### ISSUE TITLE
transcrypt: unknown option -- context

### ISSUE THREAD

**Issue by dhackelman** [elasticdog/transcrypt#170]
Has the context option been removed? 

I no longer see it in when I use the `transcrypt -h` command, and when I attempt to use the `--context` or `-C` option, I get the following error: 

```
transcrypt --context=SomeContext
transcrypt: unknown option -- context=SomeContext
usage: transcrypt [-c CIPHER] [-p PASSWORD] [-h]
```

**Comment by jmurty** [comment]
Hi, the `--context` option has not yet been included in an official _transcrypt_ release. 

You will need to use the latest code version from the `main` branch. 

If you are using the context feature successfully let me know. I have been waiting for feedback about it, good or bad, before including it in a release.

**Comment by vivekvijayakrishnan** [comment]
Hi @jmurty,

We’ve been using `--context` for some time now and it’s been working quite well. I would like to know about the roadmap for its official release, as it’s crucial for us. Could you provide an estimated timeline for when we can expect the release?

**Comment by jmurty** [comment]
Hi @vivekvijayakrishnan thanks for that feedback. I have been reluctant to make an official release with the `--context` feature since I don't use it much myself so it's not production-testing on my side, and I hadn't heard for sure whether it worked for others.

Since you are using it successfully, and I haven't heard about any problems with it, I might as well make it (more) public in a `2.3.0` release.

No promises, but I'll aim to get a new release out this week.

**Comment by jmurty** [comment]
Hi @vivekvijayakrishnan the official [transcrypt v2.3.0 release](https://github.com/elasticdog/transcrypt/releases/tag/v2.3.0) with support for contexts is now live.

Please try out this latest release and let me know if you have any problems with it.
