### ISSUE TITLE
windows version?

### ISSUE THREAD

**Issue by tcastelli** [elasticdog/transcrypt#24]
Any chance of getting a windows executable? (Actually I'm running it from minGW and works great, but would be nice to have a native version)

**Comment by elasticdog** [comment]
I'm afraid that I'm pretty far removed from the Windows ecosystem these days (I haven't owned a Windows box for ~7 years or so), and would guess that since transcrypt is based on Bash and OpenSSL, you'd have to use some compatibility layer like miniGW or Cygwin in order to satisfy those requirements.

Unless someone else has better information/background with running transcrypt in a Windows environment, I don't think I'll have time to commit to supporting it as a platform in any native sense. Closing this issue for now...
