### ISSUE TITLE
Give examples re "There are much better options if your goal is to encrypt the entire repository." 

### ISSUE THREAD

**Issue by scalp42** [elasticdog/transcrypt#36]
Regarding the statement:

    There are much better options if your goal is to encrypt the entire repository.

Any chance you could give some examples of what you're referring to?

Thanks!

**Comment by zvictor** [comment]
I came here to open an issue asking exactly the same. Found it already opened and I still have no idea what the author meant with that phrase.

**Comment by scalp42** [comment]
Might be worth pinging @elasticdog

**Comment by elasticdog** [comment]
This just means that the smudge/clean filter method of encrypting files isn't terribly efficient since it forks processes for each individual file that you want to keep secure. Any method of encrypting the entire repository (like full disk encryption, encrypted disk images, [git-remote-gcrypt](https://spwhitton.name/tech/code/git-remote-gcrypt/), etc.) would work better if you want to keep the entire thing secure. It's a much different use case than the one that transcrypt tries to solve.

**Comment by elasticdog** [comment]
Keybase also now supports [encrypted git](https://keybase.io/blog/encrypted-git-for-everyone) repository hosting, which would work well for some circumstances.

Anyway, I'll close this issue out, as I don't know if I want to maintain a list of alternatives in the repository itself. If this question comes up a lot more and people aren't satisfied being pointed here, I can reconsider.
